### ISSUE TITLE
致歉

### ISSUE THREAD

**Issue by justinbaby** [codingXiaxw/seckill#2]
首先想诚心说声抱歉，因为觉得你的readme写的很棒，所以懒得写readme copy了一份，但是未征求你的同意对此我真诚的道歉。但是我的src源码并非copy你的，而且添加了一些aop日志，存储过程，redis，test目录也没有按照imooc的写法，最后还是想说十分抱歉，抱歉，抱歉，我会移除copy你的部分

**Comment by codingXiaxw** [comment]
既然都真诚的道歉了，那我也没必要再追究了，只是我看到自己忙碌了很长时间的劳动成果被人盗用成自己的所以我心里十分气愤，这种感受你以后也会懂的！


另外你也不用再修改copy我的部分那么麻烦了，只是希望以后遇到这种事的时候你至少要懂得一点：那就是注明原作的信息，这样你才能copy的无所畏惧！所以我希望你可以在readme.md部分注明原作的地址信息！


不管是对我，还是他人，我希望你早点学到这一点。最后，还是希望你能在这条道路上越走越远！


发自网易邮箱大师
在2017年02月16日 22:25，justinbaby 写道：

首先想诚心说声抱歉，因为觉得你的readme写的很棒，所以懒得写readme copy了一份，但是未征求你的同意对此我真诚的道歉。但是我的src源码并非copy你的，而且添加了一些aop日志，存储过程，redis，test目录也没有按照imooc的写法，最后还是想说十分抱歉，抱歉，抱歉，我会移除copy你的部分

**Comment by justinbaby** [comment]
好的，感谢你的原谅，我会谨记你的话，大家一起努力加油 ：)
