### ISSUE TITLE
SeckillServiceImpl.exportSeckillUrl在并发高的时候会缓存击穿吧

### ISSUE THREAD

**Issue by chenchuxin** [codingXiaxw/seckill#22]
redis查不到的话直接查数据库，并发一来全部请求都会怼到数据库。
还有，SeckillServiceImpl.getById不加个缓存？

**Comment by codingXiaxw** [comment]
hello,谢谢指出。因为现在没有时间维护这个项目，你可以再优化这个项目后给我提个pr，欢迎你的加入

**Comment by chenchuxin** [comment]
可以可以

**Comment by codingXiaxw** [comment]
3Q，今天才抽出时间审查，发现没有冲突，已merge。谢谢你的维护～
